

平台SQL：

SELECT (UNIX_TIMESTAMP(PARSE_TIME) - UNIX_TIMESTAMP(RELEASE_TIME)) dif_second FROM WECHAT_EXCEL;

SELECT N_CODE,(UNIX_TIMESTAMP(PARSE_TIME) - UNIX_TIMESTAMP(RELEASE_TIME))/60 dif_minute FROM WECHAT_EXCEL;

# select * from WECHAT_EXCEL where (SELECT (UNIX_TIMESTAMP(PARSE_TIME) - UNIX_TIMESTAMP(RELEASE_TIME))/60 FROM WECHAT_EXCEL)>0;

# select count(*) form (SELECT (UNIX_TIMESTAMP(PARSE_TIME) - UNIX_TIMESTAMP(RELEASE_TIME))/60 FROM WECHAT_EXCEL);

SELECT COUNT(*) FROM (SELECT N_CODE,(UNIX_TIMESTAMP(PARSE_TIME) - UNIX_TIMESTAMP(RELEASE_TIME))/60 dif_minute FROM WECHAT_EXCEL) timeTable WHERE dif_minute>0 AND dif_minute<5;


测试SQL：

SELECT * FROM CRAWL_WECHAT_TASK WHERE P_TIME>='2018-12-03 00:00:00' AND P_TIME<='2018-12-04 23:59:59';  #作为子查询的一张表

SELECT COUNT(*) FROM CRAWL_WECHAT_TASK WHERE P_TIME>='2018-12-03 00:00:00' AND P_TIME<='2018-12-04 23:59:59';

SELECT N_CODE,(UNIX_TIMESTAMP(CRAWL_TIME_API) - UNIX_TIMESTAMP(P_TIME))/60 dif_minute FROM CRAWL_WECHAT_TASK;

SELECT N_CODE,(UNIX_TIMESTAMP(CRAWL_TIME_API) - UNIX_TIMESTAMP(P_TIME))/60 dif_minute FROM (SELECT * FROM CRAWL_WECHAT_TASK WHERE P_TIME>='2018-12-03 00:00:00' AND P_TIME<='2018-12-04 23:59:59') TimeTable1;

SELECT COUNT(*) FROM (SELECT N_CODE,(UNIX_TIMESTAMP(CRAWL_TIME_API) - UNIX_TIMESTAMP(P_TIME))/60 dif_minute FROM (SELECT * FROM CRAWL_WECHAT_TASK WHERE P_TIME>='2018-12-03 00:00:00' AND P_TIME<='2018-12-04 23:59:59') TimeTable1) timeTable2
WHERE dif_minute>30 AND dif_minute<=60;

SELECT COUNT(*) FROM (SELECT N_CODE,(UNIX_TIMESTAMP(CRAWL_TIME_API) - UNIX_TIMESTAMP(P_TIME))/60 dif_minute FROM (SELECT * FROM CRAWL_WECHAT_TASK WHERE P_TIME>='2018-12-03 00:00:00' AND P_TIME<='2018-12-04 23:59:59') TimeTable1) timeTable2
WHERE dif_minute>60;